apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappdeployment
  labels:
    app: mysampletomcatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysampletomcatapp
  template:
    metadata:
      labels:
        app: mysampletomcatapp
    spec:
      containers:
      - name: mysampletomcatapp
        image: asha0190/k8deployment:buildversion
        ports:
        - containerPort: 8080
